### ISSUE TITLE
rules_jvm_external

### ISSUE THREAD

**Issue by jjudd** [higherkindness/rules_scala#171]
https://github.com/bazelbuild/rules_jvm_external seems to be the rules the Bazel team is pushing for jvm third party libraries and maven support.

Do we want to investigate it, and if it meets our needs, replace our forked Bazel deps with it?

**Comment by andyscott** [comment]
👍 from me.

**Comment by jin** [comment]
Do Scala JARs need special handing around java_import? Some Kotlin JARs don't, which is what https://github.com/bazelbuild/rules_jvm_external/pull/69 is addressing.

**Comment by pauldraper** [comment]
Scala JARs need special handling if and only if they have macros.

The `ScalaInfo` provider has a `macro` boolean attribute to indicate this. If there are macros, the Scala compiler is given the runtime classpath rather than the compiler classpath.

Any non-macro JARs need no special handling.

IIRC @jjudd, Lucid had a global whitelist of macro external dependencies, and iterates through list_dependencies(), either calling java_import_external or scala_import_external depending on the result.

(This method is also why I believe that the API of bazel-deps should be list_dependencies() https://github.com/johnynek/bazel-deps/issues/153.)

**Comment by jin** [comment]
@pauldraper thanks for the explanation. In https://github.com/bazelbuild/rules_jvm_external/pull/69, all jars will not be imported by `java_import`, but a simple [Starlark `jvm_import.bzl` ](https://github.com/bazelbuild/rules_jvm_external/blob/dc69c2e1133a769fcf873ee57e0511c74b4fb46a/private/jvm_import.bzl) that places the imported jar into `JavaInfo.output_jar` and `JavaInfo.compile_jar`. There's no disambiguation between Java, Scala or Kotlin jars. This sounds like it'll work with the Scala macro JARs, is that correct?
