### ISSUE TITLE
A library cannot access resources if they are defined on a dependent binary

### ISSUE THREAD

**Issue by seanwentzel** [higherkindness/rules_scala#193]
This isn't desired because we want to be able to define multiple binaries for different environments with different resources made available.

Example: https://gist.github.com/seanwentzel/a89f994578326ec80e53c6c33ad0e59d

**Comment by borkaehw** [comment]
Thanks for providing the example. Sorry I don't quite understand what are we trying solve here. Do you mean `in_binary.txt` is not accessible by `Library.scala` because it's the resources of `scala_binary`?

**Comment by seanwentzel** [comment]
Exactly. We'd like to be able to define a second binary that exposes a different `in_binary.txt`.

**Comment by SrodriguezO** [comment]
Hey @seanwentzel, 

If I understand correctly, you have some dependency B->L (B depends on L) and you'd like L to access a file supplied by B? If so, L would have a run-time dependency on B, which means this would create a circular dependency.

If your goal is to have different resources available in different environments, a better approach might be using a `select` statement for the `resources` attribute of the base library.

**Comment by SrodriguezO** [comment]
https://docs.bazel.build/versions/master/configurable-attributes.html

**Comment by seanwentzel** [comment]
`select` is very cumbersome. For instance, if we want different resources to be available during tests, we need to explicitly set up a test Bazel platform to enable that, and the results of our tests become dependent on running them with that platform (to the best of my knowledge Bazel doesn't distinguish test builds like this already?). Effectively, we lose some degree of hermeticity in our test environment in order to statically capture runtime dependencies, which seems like a trade-off that just isn't worth it to me.

I should add that the reason this is an issue for us is that we were hoping to migrate from bazel_rules/rules_scala, which doesn't require library rules to specify their resource dependencies at runtime.

It would be interesting to see what `java_` rules do here. They're by far the most mature JVM Bazel rules, and we could probably learn a lot from their design. I'll play with them when I have the chance.

**Comment by SrodriguezO** [comment]
Hey @seanwentzel, 

Sorry for the slow response, I was out of town last week. 

> select is very cumbersome. For instance, if we want different resources to be available during tests, we need to explicitly set up a test Bazel platform to enable that

I don't think this is necessary. I think you can simply specify a [config_setting](https://docs.bazel.build/versions/master/configurable-attributes.html#configuration-conditions) for each environment for which you need different resources and then use a command-line flag to specify the environment for which you want to build (unfortunately, Bazel's [custom flags](https://docs.bazel.build/versions/master/configurable-attributes.html#custom-keys) are very rudimentary atm). Then set these config_settings as the conditions for the `select`.

>I should add that the reason this is an issue for us is that we were hoping to migrate from bazel_rules/rules_scala, which doesn't require library rules to specify their resource dependencies at runtime.

I'm glad to hear you're considering a migration! 

Irrespective of what `bazelbuild/rules_scala` does, however, I think that allowing circular dependencies between libraries and binaries is a poor practice--what if a dependent binary doesn't specify the resources the library depends on? 

I'd be interested to see what the Java rules does here.. I'd still question their decision, but like you said, they are the most mature JVM Bazel rules out there. 

@andyscott do you have any opinions on this?

--
Another option is to not use `select` at all, to instead include all resources you might need in all environments, and to specify the path to the resources you actually care about via an environment variable or system property. This may or may not be a good solution depending on your use-case.

**Comment by SeaJaredCode** [comment]
We ran into this issue as well. The use case we have is fairly similar. For the purposes of local runs, we have config file resources that need to be available, but for deployments, configuration is side loaded as a volume at container init. Using two targets one with resources and one without is the easiest way to accomplish this.

I'm not sure I understand why resources specified in the binary would not be available when running that binary. It's not compilation time, so I don't see how/why the library would be sandboxed and unable to access resources in the binary (aside from the obvious reason that they're not included). Similarly, there is no circular dependency because the library does not specify any dependency on the resource in the binary. The resources should load at runtime just as they are in a side-load production scenario -- they have no need to be declared by the library.

Also, it is inconsistent that if you make a `_deploy.jar` of the same binary target, it does include the resources as you would expect.

As a workaround, the resources _can_ be made available if packaged into a resource jar and listed as a dependency (and whitelisted). It's just awfully redundant to include as resource_jars, deps and deps_used_whitelist.

The pain of command line config_settings (and the duplicated compilation/cache) is definitely undesirable and I prefer the workaround.

**Comment by pauldraper** [comment]
A lot of noise here :)

The issue was that binary resources didn't work properly if there were no Scala sources. (Another victim of the do-six-different-things patterns established by the java_* rules.)
