### ISSUE TITLE
Question: Pinned Bazel Version

### ISSUE THREAD

**Issue by KaoruDev** [higherkindness/rules_scala#220]
Does this: https://github.com/higherkindness/rules_scala/blob/master/rules/scala/workspace.bzl#L44 mean we have to use `0.27.0`? Could we change it so users can pass in the version instead?

**Comment by SrodriguezO** [comment]
@borkaehw do you know more about this?

**Comment by borkaehw** [comment]
It looks like it's not configurable at this moment. What is the use case that you will need to change it?

**Comment by KaoruDev** [comment]
I'd like to use the latest Bazel version orthogonal to the version this library sets it to, currently the latest Bazel version is `0.28.0`

**Comment by JaredNeil** [comment]
You may be confusing something because there is no difference in this file between [`0.27.0`](https://raw.githubusercontent.com/bazelbuild/bazel/0.27.0/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt) and [`0.28.0`](https://raw.githubusercontent.com/bazelbuild/bazel/0.28.0/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt). There was a nice performance fix in the latest release though.

**Comment by KaoruDev** [comment]
yeah, my original question was whether as a consumer of higherkindness/rules_scala, do we have to use the same version specified in this file (i.e. 0.27.0)? Or is it expected that things will work fine if the versions do no align? (Sorry still new to Bazel et al).

**Comment by JaredNeil** [comment]
Ah yeah, the `0.27.0` here is just for this one script template. It theoretically could have a version incompatibility, but I haven't seen one yet, as it doesn't change very often.

**Comment by KaoruDev** [comment]
Cool, so I guess my next question, without actually knowing how things work, would it be reasonable to make this configurable when the user calls `scala_repositories`?

The alternative might be maintaining a list of Bazel versions which work with specific higherkindness/rules_scala versions.

**Comment by JaredNeil** [comment]
Yup, pretty simple. That's what https://github.com/higherkindness/rules_scala/pull/221 does.
