### ISSUE TITLE
scala_format_test vs scala_with_scalafmt.bzl

### ISSUE THREAD

**Issue by joprice** [higherkindness/rules_scala#266]
I stumbled up the rules in scala_with_scalafmt.bzl which seem to offer a different approach to formatting vs scala_format_test, where the formatting is tied into the scala_binary or scala_test rule. From the outside, this doesn't seem much different than writing a custom macro that defines a `scala_format_test` for each of the rules you need and importing that instead of the default ones. With the scala_with_scalafmt version, I couldn't figure out how to run the rules using a query.

Is there an implementation difference, or does one predate the other? The docs recommend scala_format_test, and the format script the repo uses use that approach as well. However, having a macro that wraps the two together seems like an obvious next step, and I assumed that was the intent of the rules in scala_with_scalafmt.bzl. Am I missing the intended usage? If there is a reason to prefer them, is there a way to query for any labels that use them?

**Comment by JaredNeil** [comment]
There are some slight differences. The biggest one is that you can `bazel test` the `scala_format_test`, but have to do the format checking in a more manual external-to-bazel way for the other one.
We initially added scala_with_scalafmt.bzl because we thought it might be better than a macro in some ways. And it was a interesting use of the phases architecture. After using both, I personally think the `scala_format_test` option is the better option. We (Lucid) still use the scala_with_scalafmt.bzl internally, but may switch back to `scala_format_test` eventually.
